# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'win1803'

steps:
- pwsh: |
    cd buildtools_base
    docker build -m 2GB -t marcusmaximus/msvc-buildtools-base:2019 .
  displayName: 'Build image buildtools-base'
- pwsh: |
    cd buildtools_cpp
    docker build -m 2GB -t marcusmaximus/msvc-buildtools-cpp:2019 .
  displayName: 'Build image buildtools-cpp'
- pwsh: |
    $env:DOCKERHUB_PASSWORD | docker login --username $env:DOCKERHUB_USER --password-stdin
    docker push marcusmaximus/msvc-buildtools-base:2019
    docker push marcusmaximus/msvc-buildtools-cpp:2019
    docker logout
  env: 
    DOCKERHUB_USER: $(dockerhub_user)
    DOCKERHUB_PASSWORD: $(dockerhub_password)
  displayName: 'Push images to docker hub'