# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'win1803'

steps:
#- pwsh: |
#    cd buildtools
#    docker build -t marcusmaximus/msvc-buildtools:2019 .
#  displayName: 'Build docker image'
- pwsh:
    #$env:DOCKERHUB_PASSWORD | docker login --username $env:DOCKERHUB_USER --password-stdin
    #docker push marcusmaximus/msvc-buildtools:2019
    write-host $env:DOCKERHUB_USER
  env: 
    DOCKERHUB_USER: $dockerhub_user
    DOCKERHUB_PASSWORD: $dockerhub_password
  displayName: 'Push image to docker hub'