# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

schedules:
- cron: "0 0 1 * *"
  displayName: Monthly build
  branches:
    include:
    - master
  always: true

pool:
  vmImage: 'windows-2019'

variables:
  tag_name: 'marcusmaximus/msvc-buildtools:2019-servercore-ltsc2019'
  base_image: 'mcr.microsoft.com/dotnet/framework/sdk:4.8-windowsservercore-ltsc2019'

steps:
- pwsh: |
    cd buildtools
    docker build -m 2GB -t $env:TAG_NAME --build-arg FROM_IMAGE=$env:BASE_IMAGE .
  displayName: 'Build image buildtools'
- pwsh: |
    docker run --rm $env:TAG_NAME C:\Tests.ps1
  displayName: 'Run tests'
- pwsh: |
    $env:DOCKERHUB_PASSWORD | docker login --username $env:DOCKERHUB_USER --password-stdin
    docker push $env:TAG_NAME
    docker logout
  env: 
    DOCKERHUB_USER: $(dockerhub_user)
    DOCKERHUB_PASSWORD: $(dockerhub_password)
  displayName: 'Push image to docker hub'
