# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'win1803'

steps:
- pwsh: |
    cd buildtools
    docker build -m 2GB -t marcusmaximus/msvc-buildtools:2019-servercore-1803 --build-arg FROM_IMAGE=mcr.microsoft.com/dotnet/framework/sdk:4.8-windowsservercore-1803 .
  displayName: 'Build image buildtools'
- pwsh: |
    docker run --rm marcusmaximus/msvc-buildtools:2019-servercore-1803 C:\Tests.ps1
  displayName: 'Run tests'
- pwsh: |
    $env:DOCKERHUB_PASSWORD | docker login --username $env:DOCKERHUB_USER --password-stdin
    docker push marcusmaximus/msvc-buildtools:2019
    docker logout
  env: 
    DOCKERHUB_USER: $(dockerhub_user)
    DOCKERHUB_PASSWORD: $(dockerhub_password)
  displayName: 'Push image to docker hub'