# Azure pipeline reference: https://aka.ms/yaml
pr:
  branches:
    include:
    - master
  paths:
    exclude:
    - README.md

trigger: none

pool:
  vmImage: 'windows-2019'

jobs:
- job: pull_request

  variables:
    tag_name: 'marcusmaximus/msvc-buildtools:2019-servercore-ltsc2019'
    base_image: 'mcr.microsoft.com/dotnet/framework/sdk:4.8-windowsservercore-ltsc2019'

  steps:
  - template: azure-pipelines/build_steps.yml
