FROM mcr.microsoft.com/dotnet/framework/sdk:4.8-windowsservercore-ltsc2019

SHELL [ "powershell" ]

RUN Set-ExecutionPolicy Bypass -Scope Process -Force; \
    Invoke-Expression ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))

RUN choco install -y visualstudio2019buildtools
RUN choco install -y git --params "'/GitOnlyOnPath /NoGitLfs /NoShellIntegration'"

CMD [ "powershell" ]