steps:
- pwsh: |
    cd msvc-buildtools
    docker build -m 2GB -t $env:TAG_NAME --build-arg FROM_IMAGE=$env:BASE_IMAGE .
  displayName: 'Build image'
- pwsh: |
    & msvc-buildtools\Tests.ps1 $env:TAG_NAME
  displayName: 'Run tests'