steps:
- pwsh: |
    cd msvc-buildtools
    docker build -m 2GB -t $env:TAG_NAME --build-arg FROM_IMAGE=$env:BASE_IMAGE .
  displayName: 'Build image'
- pwsh: |
    docker run --rm $env:TAG_NAME C:\Tests.ps1
  displayName: 'Run tests'